### ISSUE TITLE
Warning "No script asset for FloatTest. Check that the definition is in a file of the same name."

### ISSUE THREAD

**Issue by paulmasri** [lisandroct/EventSystem#4]
I get this warning at runtime when selecting or typing a float value into `Argument 0` of any `FloatInspector`.

Unity doesn't like `FloatTest` being defined in `FloatInspector.cs`?

**Comment by paulmasri** [comment]
This happens for all event types. Taking this example, it's because `FloatTest` is not in its own file `FloatTest.cs`.

I propose to separate tests from listeners, putting them in their own file in a `Tests` folder.

@lisandroct I plan to implement this and submit a PR imminently. Please add any comments ASAP if you want this done a certain way (or not at all).

**Comment by lisandroct** [comment]
I got used to just ignore Unity warnings since I mostly find them to report not very important noise so I didn't notice it. I think it's a good fix. Thank you for bringing it up and working on it.
