### ISSUE TITLE
Event.cs causes naming conflict with UnityEngine.Event

### ISSUE THREAD

**Issue by paulmasri** [lisandroct/EventSystem#6]
If I have code using `UnityEngine` and `lisandroct.EventSystem` then references to `Event` cause an ambiguity and the compiler defaults to expecting `UnityEngine.Event`.

```
using UnityEngine;
using lisandroct.EventSystem;

public Event myGameEvent; // I want this to refer to lisandroct.EventSystem.Event but it doesn't
```

I am forced to either replace this with

```
using UnityEngine;
using lisandroct.EventSystem;

public lisandroct.EventSystem.Event myGameEvent;
```

or

```
using UnityEngine;
using GameEvent = lisandroct.EventSystem.Event;

public GameEvent myGameEvent;
```

If I want to create one of your event assets without any arguments, on the Create menu it shows up as GameEvent.

My request is for you to rename `Event` (in Event.cs) to `GameEvent` as this would be more consistent and would also resolve the issue.

**Comment by lisandroct** [comment]
I like this. I'll look into it this week. I'm sorry, I've been super busy on another project.

**Comment by lisandroct** [comment]
Do we prefer `GameEvent` or `EmptyEvent`? Events can have any name but by default we're encouraging `'Type'Event` (for example: `FloatEvent`, `IntEvent`...), so maybe `EmptyEvent` is more consistent and clear.

**Comment by paulmasri** [comment]
I don't have a strong opinion either way. I lean towards `GameEvent` because it feels more meaningful than `EmptyEvent`.

And you already use the term `GameEvent`:

![Unity screenshot: adding a Game Event](https://user-images.githubusercontent.com/496858/129259566-cf89c109-b099-45b9-8cc0-efa8ad885af2.png)

**Comment by paulmasri** [comment]
@lisandroct Out of interest, when making a breaking change like this, do you raise the Unity package version number and do you need to provide migration for users who might be using `lisandroct.EventSystems.Event` in their scripts? I'm inexperienced in working on Unity packages.

Likewise, is it worth creating matching tags/releases here in the repo?

**Comment by lisandroct** [comment]
We should update the version in the Package definition but that by itself isn't too useful unless we also use tags (which we should). I plan to create a release with a version upgrade in the weekend.

When I first created this package I was new to the whole Package Manager. If we tag the commits, then you can import specific versions into your project.

For this change I pushed a quick hot fix and I'll set up everything in the weekend.
